### ISSUE TITLE
Data unavailable

### ISSUE THREAD

**Issue by giacomitti** [dmslabsbr/hoymiles#28] opened 2021-09-30 19:18 UTC
Sometimes the data from Hoymiles is Unavailable, is need to restart the the plugin to back work. 
But when you sse in the left menu the information is correct.

**Comment by gralin** [comment] 2021-10-09 14:11
Duplicate of https://github.com/dmslabsbr/hoymiles/issues/24 I think

**Closed** 2021-10-10 14:29 UTC
Labels: duplicate
